services:
  backend:
    container_name: brickfi-lab-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - ./shared:/shared
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: brickfi-lab-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-8000}
    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

  nginx:
    container_name: brickfi-lab-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    profiles:
      - production
